// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#ifndef _INTERFAZ_TESIS_UI_H
#define _INTERFAZ_TESIS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_splashScreen.h"
#include "ui_homeScreen.h"
#include "ui_monitoreoScreen.h"
#include "ui_configScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1571022687);    // assets/login_bg-min_11zon (1).png
LV_IMG_DECLARE(ui_img_bateria_cargando_png);    // assets/bateria_cargando.png
LV_IMG_DECLARE(ui_img_bateria_0_png);    // assets/bateria_0.png
LV_IMG_DECLARE(ui_img_bateria_25_png);    // assets/bateria_25.png
LV_IMG_DECLARE(ui_img_bateria_50_png);    // assets/bateria_50.png
LV_IMG_DECLARE(ui_img_bateria_75_png);    // assets/bateria_75.png
LV_IMG_DECLARE(ui_img_bateria_100_png);    // assets/bateria_100.png
LV_IMG_DECLARE(ui_img_acople_desconectado_png);    // assets/acople_desconectado.png
LV_IMG_DECLARE(ui_img_send_data_png);    // assets/send_data.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
