// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#include "ui.h"

// COMPONENT offButton

lv_obj_t * ui_offButton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_offButton;
    cui_offButton = lv_button_create(comp_parent);
    lv_obj_set_width(cui_offButton, 60);
    lv_obj_set_height(cui_offButton, 50);
    lv_obj_set_x(cui_offButton, 40);
    lv_obj_set_y(cui_offButton, -93);
    lv_obj_set_align(cui_offButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_offButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_offButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_offButton, lv_color_hex(0xBA2424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_offButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_offBottonLabel;
    cui_offBottonLabel = lv_label_create(cui_offButton);
    lv_obj_set_width(cui_offBottonLabel, 30);
    lv_obj_set_height(cui_offBottonLabel, 20);
    lv_obj_set_align(cui_offBottonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_offBottonLabel, "OFF");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_OFFBUTTON_NUM);
    children[UI_COMP_OFFBUTTON_OFFBUTTON] = cui_offButton;
    children[UI_COMP_OFFBUTTON_OFFBOTTONLABEL] = cui_offBottonLabel;
    lv_obj_add_event_cb(cui_offButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_offButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_offButton_create_hook(cui_offButton);
    return cui_offButton;
}

