// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#include "ui.h"

lv_obj_t * ui_configScreen = NULL;
lv_obj_t * ui_principalPanel3 = NULL;
lv_obj_t * ui_principalLabel3 = NULL;
lv_obj_t * ui_configuracionPanel = NULL;
lv_obj_t * ui_configuracionesLabel = NULL;
lv_obj_t * ui_bleContainer = NULL;
lv_obj_t * ui_bleSwitch = NULL;
lv_obj_t * ui_bleLabel = NULL;
lv_obj_t * ui_conectBLEPanel = NULL;
lv_obj_t * ui_bleOnOffLabel = NULL;
lv_obj_t * ui_brilloPanContainer2 = NULL;
lv_obj_t * ui_brilloLabel = NULL;
lv_obj_t * ui_pocentajeBrilloPanel = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_controlBrilloPanel = NULL;
lv_obj_t * ui_controlSlider = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_backLabel2 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_homeScreen_screen_init);
    }
}

// build funtions

void ui_configScreen_screen_init(void)
{
    ui_configScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_configScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_principalPanel3 = lv_obj_create(ui_configScreen);
    lv_obj_set_width(ui_principalPanel3, 326);
    lv_obj_set_height(ui_principalPanel3, 50);
    lv_obj_set_x(ui_principalPanel3, 0);
    lv_obj_set_y(ui_principalPanel3, -220);
    lv_obj_set_align(ui_principalPanel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_principalPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_principalPanel3, lv_color_hex(0x6660DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_principalPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_principalLabel3 = lv_label_create(ui_principalPanel3);
    lv_obj_set_width(ui_principalLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_principalLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_principalLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_principalLabel3, "Tanari DP");
    lv_obj_set_style_text_color(ui_principalLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_principalLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_principalLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_principalLabel3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configuracionPanel = lv_obj_create(ui_configScreen);
    lv_obj_set_width(ui_configuracionPanel, 280);
    lv_obj_set_height(ui_configuracionPanel, 356);
    lv_obj_set_x(ui_configuracionPanel, 0);
    lv_obj_set_y(ui_configuracionPanel, -10);
    lv_obj_set_align(ui_configuracionPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_configuracionPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_configuracionPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_configuracionPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_configuracionPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_configuracionPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_color(ui_configuracionPanel, lv_color_hex(0x922F2F), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_configuracionesLabel = lv_label_create(ui_configuracionPanel);
    lv_obj_set_width(ui_configuracionesLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_configuracionesLabel, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_configuracionesLabel, "CONGIFURACIONES");
    lv_obj_set_style_text_font(ui_configuracionesLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bleContainer = lv_obj_create(ui_configuracionPanel);
    lv_obj_remove_style_all(ui_bleContainer);
    lv_obj_set_width(ui_bleContainer, 235);
    lv_obj_set_height(ui_bleContainer, 165);
    lv_obj_set_x(ui_bleContainer, 0);
    lv_obj_set_y(ui_bleContainer, -81);
    lv_obj_set_align(ui_bleContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_bleContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bleSwitch = lv_switch_create(ui_bleContainer);
    lv_obj_set_width(ui_bleSwitch, 90);
    lv_obj_set_height(ui_bleSwitch, 40);
    lv_obj_set_x(ui_bleSwitch, 60);
    lv_obj_set_y(ui_bleSwitch, 0);
    lv_obj_set_align(ui_bleSwitch, LV_ALIGN_CENTER);

    ui_bleLabel = lv_label_create(ui_bleContainer);
    lv_obj_set_width(ui_bleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bleLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_bleLabel, "BLE");
    lv_obj_set_style_text_font(ui_bleLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conectBLEPanel = lv_obj_create(ui_bleContainer);
    lv_obj_set_width(ui_conectBLEPanel, 150);
    lv_obj_set_height(ui_conectBLEPanel, 50);
    lv_obj_set_x(ui_conectBLEPanel, 0);
    lv_obj_set_y(ui_conectBLEPanel, 58);
    lv_obj_set_align(ui_conectBLEPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_conectBLEPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bleOnOffLabel = lv_label_create(ui_conectBLEPanel);
    lv_obj_set_width(ui_bleOnOffLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bleOnOffLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bleOnOffLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bleOnOffLabel, "text");

    ui_brilloPanContainer2 = lv_obj_create(ui_configuracionPanel);
    lv_obj_remove_style_all(ui_brilloPanContainer2);
    lv_obj_set_width(ui_brilloPanContainer2, 230);
    lv_obj_set_height(ui_brilloPanContainer2, 232);
    lv_obj_set_x(ui_brilloPanContainer2, 0);
    lv_obj_set_y(ui_brilloPanContainer2, 57);
    lv_obj_set_align(ui_brilloPanContainer2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_brilloPanContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_brilloLabel = lv_label_create(ui_brilloPanContainer2);
    lv_obj_set_width(ui_brilloLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brilloLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_brilloLabel, 0);
    lv_obj_set_y(ui_brilloLabel, -10);
    lv_obj_set_align(ui_brilloLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_brilloLabel, "Brillo");
    lv_obj_set_style_text_font(ui_brilloLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pocentajeBrilloPanel = lv_obj_create(ui_brilloPanContainer2);
    lv_obj_set_width(ui_pocentajeBrilloPanel, 58);
    lv_obj_set_height(ui_pocentajeBrilloPanel, 40);
    lv_obj_set_x(ui_pocentajeBrilloPanel, 0);
    lv_obj_set_y(ui_pocentajeBrilloPanel, 36);
    lv_obj_set_align(ui_pocentajeBrilloPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pocentajeBrilloPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_pocentajeBrilloPanel);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "text");

    ui_controlBrilloPanel = lv_obj_create(ui_brilloPanContainer2);
    lv_obj_set_width(ui_controlBrilloPanel, 225);
    lv_obj_set_height(ui_controlBrilloPanel, 40);
    lv_obj_set_x(ui_controlBrilloPanel, 0);
    lv_obj_set_y(ui_controlBrilloPanel, 86);
    lv_obj_set_align(ui_controlBrilloPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_controlBrilloPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_controlBrilloPanel, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_controlBrilloPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_controlSlider = lv_slider_create(ui_controlBrilloPanel);
    lv_slider_set_value(ui_controlSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_controlSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_controlSlider, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_controlSlider, 175);
    lv_obj_set_height(ui_controlSlider, 10);
    lv_obj_set_align(ui_controlSlider, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_controlSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_controlSlider,
                                                                                                    lv_obj_get_style_pad_right(ui_controlSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Button3 = lv_button_create(ui_configScreen);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 0);
    lv_obj_set_y(ui_Button3, 207);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backLabel2 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_backLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_backLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backLabel2, "Regresar");
    lv_obj_set_style_text_font(ui_backLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_configScreen_screen_destroy(void)
{
    if(ui_configScreen) lv_obj_del(ui_configScreen);

    // NULL screen variables
    ui_configScreen = NULL;
    ui_principalPanel3 = NULL;
    ui_principalLabel3 = NULL;
    ui_configuracionPanel = NULL;
    ui_configuracionesLabel = NULL;
    ui_bleContainer = NULL;
    ui_bleSwitch = NULL;
    ui_bleLabel = NULL;
    ui_conectBLEPanel = NULL;
    ui_bleOnOffLabel = NULL;
    ui_brilloPanContainer2 = NULL;
    ui_brilloLabel = NULL;
    ui_pocentajeBrilloPanel = NULL;
    ui_Label2 = NULL;
    ui_controlBrilloPanel = NULL;
    ui_controlSlider = NULL;
    ui_Button3 = NULL;
    ui_backLabel2 = NULL;

}
