// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#ifndef _UI_COMP_OFFBUTTON1_H
#define _UI_COMP_OFFBUTTON1_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT offButton1
#define UI_COMP_OFFBUTTON1_OFFBUTTON1 0
#define UI_COMP_OFFBUTTON1_OFFBOTTONLABEL1 1
#define _UI_COMP_OFFBUTTON1_NUM 2
lv_obj_t * ui_offButton1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
