// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#ifndef _UI_COMP_CONFIGUREBUTTON_H
#define _UI_COMP_CONFIGUREBUTTON_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT configureButton
#define UI_COMP_CONFIGUREBUTTON_CONFIGUREBUTTON 0
#define UI_COMP_CONFIGUREBUTTON_CONFIGUREBOTTONLABEL 1
#define _UI_COMP_CONFIGUREBUTTON_NUM 2
lv_obj_t * ui_configureButton_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
