// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#include "ui.h"

// COMPONENT offButton1

lv_obj_t * ui_offButton1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_offButton1;
    cui_offButton1 = lv_button_create(comp_parent);
    lv_obj_set_width(cui_offButton1, 60);
    lv_obj_set_height(cui_offButton1, 50);
    lv_obj_set_x(cui_offButton1, 40);
    lv_obj_set_y(cui_offButton1, -93);
    lv_obj_set_align(cui_offButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_offButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_offButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_offButton1, lv_color_hex(0xBA2424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_offButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_offBottonLabel1;
    cui_offBottonLabel1 = lv_label_create(cui_offButton1);
    lv_obj_set_width(cui_offBottonLabel1, 30);
    lv_obj_set_height(cui_offBottonLabel1, 20);
    lv_obj_set_align(cui_offBottonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_offBottonLabel1, "OFF");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_OFFBUTTON1_NUM);
    children[UI_COMP_OFFBUTTON1_OFFBUTTON1] = cui_offButton1;
    children[UI_COMP_OFFBUTTON1_OFFBOTTONLABEL1] = cui_offBottonLabel1;
    lv_obj_add_event_cb(cui_offButton1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_offButton1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_offButton1_create_hook(cui_offButton1);
    return cui_offButton1;
}

