// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#ifndef _INTERFAZ_TESIS_UI_COMP_HOOK_H
#define _INTERFAZ_TESIS_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_configureButton_create_hook(lv_obj_t * comp);
void ui_comp_offButton_create_hook(lv_obj_t * comp);
void ui_comp_offButton1_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
