// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#include "ui.h"

void ui_comp_configureButton_create_hook(lv_obj_t * comp)
{
}

void ui_comp_offButton_create_hook(lv_obj_t * comp)
{
}

void ui_comp_offButton1_create_hook(lv_obj_t * comp)
{
}
