// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#include "ui.h"

// COMPONENT configureButton

lv_obj_t * ui_configureButton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_configureButton;
    cui_configureButton = lv_button_create(comp_parent);
    lv_obj_set_width(cui_configureButton, 140);
    lv_obj_set_height(cui_configureButton, 50);
    lv_obj_set_x(cui_configureButton, -4);
    lv_obj_set_y(cui_configureButton, 157);
    lv_obj_set_align(cui_configureButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_configureButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_configureButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_configureButton, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_configureButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_configureBottonLabel;
    cui_configureBottonLabel = lv_label_create(cui_configureButton);
    lv_obj_set_width(cui_configureBottonLabel, 80);
    lv_obj_set_height(cui_configureBottonLabel, 20);
    lv_obj_set_align(cui_configureBottonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_configureBottonLabel, "Configure");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONFIGUREBUTTON_NUM);
    children[UI_COMP_CONFIGUREBUTTON_CONFIGUREBUTTON] = cui_configureButton;
    children[UI_COMP_CONFIGUREBUTTON_CONFIGUREBOTTONLABEL] = cui_configureBottonLabel;
    lv_obj_add_event_cb(cui_configureButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_configureButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_configureButton_create_hook(cui_configureButton);
    return cui_configureButton;
}

