// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void mostrarSensorCO2Valor(lv_event_t * e);
void mostrarSensorCH4Valor(lv_event_t * e);
void mostrarSensorTEMPValor(lv_event_t * e);
void mostrarSensorHUMValor(lv_event_t * e);

void ui_event_bleSwitch(lv_event_t * e);
void ui_event_controlSlider(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
