// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

/* --- Eventos de la Pantalla de Monitoreo (YA EXISTENTES) --- */
void mostrarSensorCO2Valor(lv_event_t * e);
void mostrarSensorCH4Valor(lv_event_t * e);
void mostrarSensorTEMPValor(lv_event_t * e);
void mostrarSensorHUMValor(lv_event_t * e);

/* --- Eventos de la Pantalla de Configuración (NUEVOS) --- */
void ui_event_bleSwitch(lv_event_t * e);
void ui_event_controlSlider(lv_event_t * e);
void ui_event_Button3(lv_event_t * e); // Evento para el botón "Regresar" de la pantalla de config

// *******************************************************************
// ¡IMPORTANTE! Añade la declaración de esta función aquí
void updateBLEStatusLabel(void); // Declaración de la función para actualizar el estado del BLE en la UI
// *******************************************************************

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif