// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_homeScreen
extern void ui_homeScreen_screen_init(void);
extern void ui_homeScreen_screen_destroy(void);
extern lv_obj_t * ui_homeScreen;
extern lv_obj_t * ui_principalPanel2;
extern lv_obj_t * ui_principalLabel2;
extern lv_obj_t * ui_menuPanel;
extern lv_obj_t * ui_configuracionesLabel2;
extern void ui_event_homeButton(lv_event_t * e);
extern lv_obj_t * ui_homeButton;
extern lv_obj_t * ui_monitorLabel;
extern void ui_event_confiButton(lv_event_t * e);
extern lv_obj_t * ui_confiButton;
extern lv_obj_t * ui_confiLabel;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_backLabel3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

