// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#include "ui.h"

lv_obj_t * ui_homeScreen = NULL;
lv_obj_t * ui_principalPanel2 = NULL;
lv_obj_t * ui_principalLabel2 = NULL;
lv_obj_t * ui_menuPanel = NULL;
lv_obj_t * ui_configuracionesLabel2 = NULL;
lv_obj_t * ui_homeButton = NULL;
lv_obj_t * ui_monitorLabel = NULL;
lv_obj_t * ui_confiButton = NULL;
lv_obj_t * ui_confiLabel = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_backLabel3 = NULL;
// event funtions
void ui_event_homeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_monitoreoScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_monitoreoScreen_screen_init);
    }
}

void ui_event_confiButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_configScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_configScreen_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_splashScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_splashScreen_screen_init);
    }
}

// build funtions

void ui_homeScreen_screen_init(void)
{
    ui_homeScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_homeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_principalPanel2 = lv_obj_create(ui_homeScreen);
    lv_obj_set_width(ui_principalPanel2, 326);
    lv_obj_set_height(ui_principalPanel2, 50);
    lv_obj_set_x(ui_principalPanel2, 0);
    lv_obj_set_y(ui_principalPanel2, -220);
    lv_obj_set_align(ui_principalPanel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_principalPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_principalPanel2, lv_color_hex(0x6660DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_principalPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_principalLabel2 = lv_label_create(ui_principalPanel2);
    lv_obj_set_width(ui_principalLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_principalLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_principalLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_principalLabel2, "Tanari DP");
    lv_obj_set_style_text_color(ui_principalLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_principalLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_principalLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_principalLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuPanel = lv_obj_create(ui_homeScreen);
    lv_obj_set_width(ui_menuPanel, 280);
    lv_obj_set_height(ui_menuPanel, 340);
    lv_obj_set_x(ui_menuPanel, 0);
    lv_obj_set_y(ui_menuPanel, -10);
    lv_obj_set_align(ui_menuPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_menuPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menuPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menuPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_menuPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_menuPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_color(ui_menuPanel, lv_color_hex(0x922F2F), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_configuracionesLabel2 = lv_label_create(ui_menuPanel);
    lv_obj_set_width(ui_configuracionesLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_configuracionesLabel2, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_configuracionesLabel2, "MENU\n");
    lv_obj_set_style_text_font(ui_configuracionesLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeButton = lv_button_create(ui_menuPanel);
    lv_obj_set_width(ui_homeButton, 200);
    lv_obj_set_height(ui_homeButton, 50);
    lv_obj_set_x(ui_homeButton, 0);
    lv_obj_set_y(ui_homeButton, -60);
    lv_obj_set_align(ui_homeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homeButton, lv_color_hex(0x0EC34E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_monitorLabel = lv_label_create(ui_homeButton);
    lv_obj_set_width(ui_monitorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_monitorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_monitorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_monitorLabel, "MONITOREO");
    lv_obj_set_style_text_font(ui_monitorLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confiButton = lv_button_create(ui_menuPanel);
    lv_obj_set_width(ui_confiButton, 200);
    lv_obj_set_height(ui_confiButton, 50);
    lv_obj_set_x(ui_confiButton, 0);
    lv_obj_set_y(ui_confiButton, 60);
    lv_obj_set_align(ui_confiButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_confiButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_confiButton, lv_color_hex(0x0EC34E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_confiButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confiLabel = lv_label_create(ui_confiButton);
    lv_obj_set_width(ui_confiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_confiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_confiLabel, "CONFIGURACION");
    lv_obj_set_style_text_align(ui_confiLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_confiLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_homeScreen);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, 205);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backLabel3 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_backLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_backLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backLabel3, "Regresar");
    lv_obj_set_style_text_font(ui_backLabel3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_homeButton, ui_event_homeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_confiButton, ui_event_confiButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}

void ui_homeScreen_screen_destroy(void)
{
    if(ui_homeScreen) lv_obj_del(ui_homeScreen);

    // NULL screen variables
    ui_homeScreen = NULL;
    ui_principalPanel2 = NULL;
    ui_principalLabel2 = NULL;
    ui_menuPanel = NULL;
    ui_configuracionesLabel2 = NULL;
    ui_homeButton = NULL;
    ui_monitorLabel = NULL;
    ui_confiButton = NULL;
    ui_confiLabel = NULL;
    ui_Button4 = NULL;
    ui_backLabel3 = NULL;

}
