// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#include "ui.h"

lv_obj_t * ui_monitoreoScreen = NULL;
lv_obj_t * ui_principalPanel2 = NULL;
lv_obj_t * ui_principalLabel3 = NULL;
lv_obj_t * ui_EstadoBateriaContainer2 = NULL;
lv_obj_t * ui_bateria0Image2 = NULL;
lv_obj_t * ui_batPorcentajeLabel2 = NULL;
lv_obj_t * ui_EstadoAcopleContainer2 = NULL;
lv_obj_t * ui_offAcoplePanel2 = NULL;
lv_obj_t * ui_onAcoplePanel2 = NULL;
lv_obj_t * ui_sendBLEContainer2 = NULL;
lv_obj_t * ui_offBLEPanel2 = NULL;
lv_obj_t * ui_desconectadoBLEPanel2 = NULL;
lv_obj_t * ui_conectadoBLEPanel2 = NULL;
lv_obj_t * ui_monitoreoPanel = NULL;
lv_obj_t * ui_monitoreoLabel = NULL;
lv_obj_t * ui_CO2Container = NULL;
lv_obj_t * ui_co2Label = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_resulCO2Label = NULL;
lv_obj_t * ui_CH4Container = NULL;
lv_obj_t * ui_CH4Label = NULL;
lv_obj_t * ui_resulCH4Panel = NULL;
lv_obj_t * ui_resulCH4Label = NULL;
lv_obj_t * ui_tempContainer = NULL;
lv_obj_t * ui_tempLabel = NULL;
lv_obj_t * ui_resulTempPanel = NULL;
lv_obj_t * ui_resulTempLabel = NULL;
lv_obj_t * ui_humedContainer = NULL;
lv_obj_t * ui_resulhumedLabel = NULL;
lv_obj_t * ui_resulHumedPanel = NULL;
lv_obj_t * ui_resulHumLabel = NULL;
lv_obj_t * ui_backButton2 = NULL;
lv_obj_t * ui_backLabel2 = NULL;
// event funtions
void ui_event_resulCO2Label(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        mostrarSensorCO2Valor(e);
    }
}

void ui_event_resulCH4Label(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        mostrarSensorCH4Valor(e);
    }
}

void ui_event_resulTempLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        mostrarSensorTEMPValor(e);
    }
}

void ui_event_resulHumLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        mostrarSensorHUMValor(e);
    }
}

void ui_event_backButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_homeScreen_screen_init);
    }
}

// build funtions

void ui_monitoreoScreen_screen_init(void)
{
    ui_monitoreoScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_monitoreoScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_principalPanel2 = lv_obj_create(ui_monitoreoScreen);
    lv_obj_set_width(ui_principalPanel2, 326);
    lv_obj_set_height(ui_principalPanel2, 50);
    lv_obj_set_x(ui_principalPanel2, 0);
    lv_obj_set_y(ui_principalPanel2, -220);
    lv_obj_set_align(ui_principalPanel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_principalPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_principalPanel2, lv_color_hex(0x6660DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_principalPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_principalLabel3 = lv_label_create(ui_principalPanel2);
    lv_obj_set_width(ui_principalLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_principalLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_principalLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_principalLabel3, "Tanari DP");
    lv_obj_set_style_text_color(ui_principalLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_principalLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_principalLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_principalLabel3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EstadoBateriaContainer2 = lv_obj_create(ui_principalPanel2);
    lv_obj_remove_style_all(ui_EstadoBateriaContainer2);
    lv_obj_set_width(ui_EstadoBateriaContainer2, 80);
    lv_obj_set_height(ui_EstadoBateriaContainer2, 50);
    lv_obj_set_x(ui_EstadoBateriaContainer2, 121);
    lv_obj_set_y(ui_EstadoBateriaContainer2, 1);
    lv_obj_set_align(ui_EstadoBateriaContainer2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_EstadoBateriaContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bateria0Image2 = lv_image_create(ui_EstadoBateriaContainer2);
    lv_image_set_src(ui_bateria0Image2, &ui_img_660791701);
    lv_obj_set_width(ui_bateria0Image2, 50);
    lv_obj_set_height(ui_bateria0Image2, 40);
    lv_obj_set_x(ui_bateria0Image2, 1);
    lv_obj_set_y(ui_bateria0Image2, 0);
    lv_obj_set_align(ui_bateria0Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bateria0Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_bateria0Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_bateria0Image2, 27);

    ui_batPorcentajeLabel2 = lv_label_create(ui_bateria0Image2);
    lv_obj_set_width(ui_batPorcentajeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batPorcentajeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batPorcentajeLabel2, -1);
    lv_obj_set_y(ui_batPorcentajeLabel2, 0);
    lv_obj_set_align(ui_batPorcentajeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batPorcentajeLabel2, "");
    lv_obj_set_style_text_color(ui_batPorcentajeLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_batPorcentajeLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_batPorcentajeLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EstadoAcopleContainer2 = lv_obj_create(ui_principalPanel2);
    lv_obj_remove_style_all(ui_EstadoAcopleContainer2);
    lv_obj_set_width(ui_EstadoAcopleContainer2, 40);
    lv_obj_set_height(ui_EstadoAcopleContainer2, 35);
    lv_obj_set_x(ui_EstadoAcopleContainer2, -133);
    lv_obj_set_y(ui_EstadoAcopleContainer2, 1);
    lv_obj_set_align(ui_EstadoAcopleContainer2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_EstadoAcopleContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_offAcoplePanel2 = lv_obj_create(ui_EstadoAcopleContainer2);
    lv_obj_set_width(ui_offAcoplePanel2, 25);
    lv_obj_set_height(ui_offAcoplePanel2, 25);
    lv_obj_set_align(ui_offAcoplePanel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_offAcoplePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_offAcoplePanel2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_offAcoplePanel2, lv_color_hex(0xE1DADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_offAcoplePanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_onAcoplePanel2 = lv_obj_create(ui_EstadoAcopleContainer2);
    lv_obj_set_width(ui_onAcoplePanel2, 25);
    lv_obj_set_height(ui_onAcoplePanel2, 25);
    lv_obj_set_align(ui_onAcoplePanel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_onAcoplePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_onAcoplePanel2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_onAcoplePanel2, lv_color_hex(0x22EA41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_onAcoplePanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sendBLEContainer2 = lv_obj_create(ui_principalPanel2);
    lv_obj_remove_style_all(ui_sendBLEContainer2);
    lv_obj_set_width(ui_sendBLEContainer2, 40);
    lv_obj_set_height(ui_sendBLEContainer2, 35);
    lv_obj_set_x(ui_sendBLEContainer2, -90);
    lv_obj_set_y(ui_sendBLEContainer2, 1);
    lv_obj_set_align(ui_sendBLEContainer2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_sendBLEContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_offBLEPanel2 = lv_obj_create(ui_sendBLEContainer2);
    lv_obj_set_width(ui_offBLEPanel2, 25);
    lv_obj_set_height(ui_offBLEPanel2, 25);
    lv_obj_set_align(ui_offBLEPanel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_offBLEPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_offBLEPanel2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_offBLEPanel2, lv_color_hex(0xE1DADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_offBLEPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_desconectadoBLEPanel2 = lv_obj_create(ui_sendBLEContainer2);
    lv_obj_set_width(ui_desconectadoBLEPanel2, 25);
    lv_obj_set_height(ui_desconectadoBLEPanel2, 25);
    lv_obj_set_align(ui_desconectadoBLEPanel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_desconectadoBLEPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_desconectadoBLEPanel2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_desconectadoBLEPanel2, lv_color_hex(0xF49202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_desconectadoBLEPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conectadoBLEPanel2 = lv_obj_create(ui_sendBLEContainer2);
    lv_obj_set_width(ui_conectadoBLEPanel2, 25);
    lv_obj_set_height(ui_conectadoBLEPanel2, 25);
    lv_obj_set_align(ui_conectadoBLEPanel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_conectadoBLEPanel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_conectadoBLEPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_conectadoBLEPanel2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_conectadoBLEPanel2, lv_color_hex(0x22EA41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conectadoBLEPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_monitoreoPanel = lv_obj_create(ui_monitoreoScreen);
    lv_obj_set_width(ui_monitoreoPanel, 280);
    lv_obj_set_height(ui_monitoreoPanel, 356);
    lv_obj_set_x(ui_monitoreoPanel, 0);
    lv_obj_set_y(ui_monitoreoPanel, -9);
    lv_obj_set_align(ui_monitoreoPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_monitoreoPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_monitoreoPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_monitoreoPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_monitoreoPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_monitoreoPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_color(ui_monitoreoPanel, lv_color_hex(0x922F2F), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_monitoreoLabel = lv_label_create(ui_monitoreoPanel);
    lv_obj_set_width(ui_monitoreoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_monitoreoLabel, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_monitoreoLabel, "MONITOREO");

    ui_CO2Container = lv_obj_create(ui_monitoreoPanel);
    lv_obj_remove_style_all(ui_CO2Container);
    lv_obj_set_width(ui_CO2Container, 230);
    lv_obj_set_height(ui_CO2Container, 50);
    lv_obj_set_x(ui_CO2Container, 0);
    lv_obj_set_y(ui_CO2Container, -93);
    lv_obj_set_align(ui_CO2Container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CO2Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_co2Label = lv_label_create(ui_CO2Container);
    lv_obj_set_width(ui_co2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_co2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_co2Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_co2Label, "CO2: ");
    lv_obj_set_style_text_font(ui_co2Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_CO2Container);
    lv_obj_set_width(ui_Panel1, 150);
    lv_obj_set_height(ui_Panel1, 40);
    lv_obj_set_x(ui_Panel1, 31);
    lv_obj_set_y(ui_Panel1, 2);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resulCO2Label = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_resulCO2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_resulCO2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_resulCO2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_resulCO2Label, "text");

    ui_CH4Container = lv_obj_create(ui_monitoreoPanel);
    lv_obj_remove_style_all(ui_CH4Container);
    lv_obj_set_width(ui_CH4Container, 230);
    lv_obj_set_height(ui_CH4Container, 50);
    lv_obj_set_x(ui_CH4Container, 0);
    lv_obj_set_y(ui_CH4Container, -24);
    lv_obj_set_align(ui_CH4Container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CH4Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CH4Label = lv_label_create(ui_CH4Container);
    lv_obj_set_width(ui_CH4Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CH4Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CH4Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CH4Label, "CH4: ");
    lv_obj_set_style_text_font(ui_CH4Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resulCH4Panel = lv_obj_create(ui_CH4Container);
    lv_obj_set_width(ui_resulCH4Panel, 150);
    lv_obj_set_height(ui_resulCH4Panel, 40);
    lv_obj_set_x(ui_resulCH4Panel, 30);
    lv_obj_set_y(ui_resulCH4Panel, 2);
    lv_obj_set_align(ui_resulCH4Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_resulCH4Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_resulCH4Panel, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_resulCH4Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resulCH4Label = lv_label_create(ui_resulCH4Panel);
    lv_obj_set_width(ui_resulCH4Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_resulCH4Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_resulCH4Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_resulCH4Label, "text");

    ui_tempContainer = lv_obj_create(ui_monitoreoPanel);
    lv_obj_remove_style_all(ui_tempContainer);
    lv_obj_set_width(ui_tempContainer, 253);
    lv_obj_set_height(ui_tempContainer, 50);
    lv_obj_set_x(ui_tempContainer, 0);
    lv_obj_set_y(ui_tempContainer, 50);
    lv_obj_set_align(ui_tempContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_tempContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempLabel = lv_label_create(ui_tempContainer);
    lv_obj_set_width(ui_tempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tempLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_tempLabel, "Temp: ");
    lv_obj_set_style_text_font(ui_tempLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resulTempPanel = lv_obj_create(ui_tempContainer);
    lv_obj_set_width(ui_resulTempPanel, 150);
    lv_obj_set_height(ui_resulTempPanel, 40);
    lv_obj_set_x(ui_resulTempPanel, 30);
    lv_obj_set_y(ui_resulTempPanel, 2);
    lv_obj_set_align(ui_resulTempPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_resulTempPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_resulTempPanel, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_resulTempPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resulTempLabel = lv_label_create(ui_resulTempPanel);
    lv_obj_set_width(ui_resulTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_resulTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_resulTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_resulTempLabel, "text");

    ui_humedContainer = lv_obj_create(ui_monitoreoPanel);
    lv_obj_remove_style_all(ui_humedContainer);
    lv_obj_set_width(ui_humedContainer, 253);
    lv_obj_set_height(ui_humedContainer, 50);
    lv_obj_set_x(ui_humedContainer, 0);
    lv_obj_set_y(ui_humedContainer, 120);
    lv_obj_set_align(ui_humedContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_humedContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_resulhumedLabel = lv_label_create(ui_humedContainer);
    lv_obj_set_width(ui_resulhumedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_resulhumedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_resulhumedLabel, 5);
    lv_obj_set_y(ui_resulhumedLabel, 0);
    lv_obj_set_align(ui_resulhumedLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_resulhumedLabel, "Hum: ");
    lv_obj_set_style_text_font(ui_resulhumedLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resulHumedPanel = lv_obj_create(ui_humedContainer);
    lv_obj_set_width(ui_resulHumedPanel, 150);
    lv_obj_set_height(ui_resulHumedPanel, 40);
    lv_obj_set_x(ui_resulHumedPanel, 30);
    lv_obj_set_y(ui_resulHumedPanel, 2);
    lv_obj_set_align(ui_resulHumedPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_resulHumedPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_resulHumedPanel, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_resulHumedPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resulHumLabel = lv_label_create(ui_resulHumedPanel);
    lv_obj_set_width(ui_resulHumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_resulHumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_resulHumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_resulHumLabel, "text");

    ui_backButton2 = lv_button_create(ui_monitoreoScreen);
    lv_obj_set_width(ui_backButton2, 100);
    lv_obj_set_height(ui_backButton2, 50);
    lv_obj_set_x(ui_backButton2, 0);
    lv_obj_set_y(ui_backButton2, 207);
    lv_obj_set_align(ui_backButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backButton2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backLabel2 = lv_label_create(ui_backButton2);
    lv_obj_set_width(ui_backLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_backLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backLabel2, "Regresar");
    lv_obj_set_style_text_font(ui_backLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_resulCO2Label, ui_event_resulCO2Label, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_resulCH4Label, ui_event_resulCH4Label, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_resulTempLabel, ui_event_resulTempLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_resulHumLabel, ui_event_resulHumLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backButton2, ui_event_backButton2, LV_EVENT_ALL, NULL);

}

void ui_monitoreoScreen_screen_destroy(void)
{
    if(ui_monitoreoScreen) lv_obj_del(ui_monitoreoScreen);

    // NULL screen variables
    ui_monitoreoScreen = NULL;
    ui_principalPanel2 = NULL;
    ui_principalLabel3 = NULL;
    ui_EstadoBateriaContainer2 = NULL;
    ui_bateria0Image2 = NULL;
    ui_batPorcentajeLabel2 = NULL;
    ui_EstadoAcopleContainer2 = NULL;
    ui_offAcoplePanel2 = NULL;
    ui_onAcoplePanel2 = NULL;
    ui_sendBLEContainer2 = NULL;
    ui_offBLEPanel2 = NULL;
    ui_desconectadoBLEPanel2 = NULL;
    ui_conectadoBLEPanel2 = NULL;
    ui_monitoreoPanel = NULL;
    ui_monitoreoLabel = NULL;
    ui_CO2Container = NULL;
    ui_co2Label = NULL;
    ui_Panel1 = NULL;
    ui_resulCO2Label = NULL;
    ui_CH4Container = NULL;
    ui_CH4Label = NULL;
    ui_resulCH4Panel = NULL;
    ui_resulCH4Label = NULL;
    ui_tempContainer = NULL;
    ui_tempLabel = NULL;
    ui_resulTempPanel = NULL;
    ui_resulTempLabel = NULL;
    ui_humedContainer = NULL;
    ui_resulhumedLabel = NULL;
    ui_resulHumedPanel = NULL;
    ui_resulHumLabel = NULL;
    ui_backButton2 = NULL;
    ui_backLabel2 = NULL;

}
