// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#ifndef UI_MONITOREOSCREEN_H
#define UI_MONITOREOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_monitoreoScreen
extern void ui_monitoreoScreen_screen_init(void);
extern void ui_monitoreoScreen_screen_destroy(void);
extern lv_obj_t * ui_monitoreoScreen;
extern lv_obj_t * ui_principalPanel;
extern lv_obj_t * ui_principalLabel;
extern lv_obj_t * ui_monitoreoPanel;
extern lv_obj_t * ui_monitoreoLabel;
extern lv_obj_t * ui_CO2Container;
extern lv_obj_t * ui_co2Label;
extern lv_obj_t * ui_Panel1;
extern void ui_event_resulCO2Label(lv_event_t * e);
extern lv_obj_t * ui_resulCO2Label;
extern lv_obj_t * ui_CH4Container;
extern lv_obj_t * ui_CH4Label;
extern lv_obj_t * ui_resulCH4Panel;
extern void ui_event_resulCH4Label(lv_event_t * e);
extern lv_obj_t * ui_resulCH4Label;
extern lv_obj_t * ui_tempContainer;
extern lv_obj_t * ui_tempLabel;
extern lv_obj_t * ui_resulTempPanel;
extern void ui_event_resulTempLabel(lv_event_t * e);
extern lv_obj_t * ui_resulTempLabel;
extern lv_obj_t * ui_humedContainer;
extern lv_obj_t * ui_resulhumedLabel;
extern lv_obj_t * ui_resulHumedPanel;
extern void ui_event_resulHumLabel(lv_event_t * e);
extern lv_obj_t * ui_resulHumLabel;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_backLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

