// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#ifndef UI_SPLASHSCREEN_H
#define UI_SPLASHSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_splashScreen
extern void ui_splashScreen_screen_init(void);
extern void ui_splashScreen_screen_destroy(void);
extern lv_obj_t * ui_splashScreen;
extern lv_obj_t * ui_welcomeBgImage;
extern lv_obj_t * ui_bienvenidosLabel;
extern lv_obj_t * ui_aLabel;
extern lv_obj_t * ui_tanariDPLabel;
extern void ui_event_iniciarButton(lv_event_t * e);
extern lv_obj_t * ui_iniciarButton;
extern lv_obj_t * ui_iniciarLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

