// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Interfaz_Tesis

#include "ui.h"

lv_obj_t * ui_splashScreen = NULL;
lv_obj_t * ui_bienvenidoImagen = NULL;
lv_obj_t * ui_bienvenidosLabel = NULL;
lv_obj_t * ui_aLabel = NULL;
lv_obj_t * ui_tanariDPLabel = NULL;
lv_obj_t * ui_iniciarButton = NULL;
lv_obj_t * ui_iniciarLabel = NULL;
// event funtions
void ui_event_iniciarButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_homeScreen_screen_init);
    }
}

// build funtions

void ui_splashScreen_screen_init(void)
{
    ui_splashScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_splashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bienvenidoImagen = lv_image_create(ui_splashScreen);
    lv_image_set_src(ui_bienvenidoImagen, &ui_img_1571022687);
    lv_obj_set_width(ui_bienvenidoImagen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bienvenidoImagen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bienvenidoImagen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bienvenidoImagen, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_bienvenidoImagen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_bienvenidoImagen, 330);

    ui_bienvenidosLabel = lv_label_create(ui_splashScreen);
    lv_obj_set_width(ui_bienvenidosLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bienvenidosLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bienvenidosLabel, 2);
    lv_obj_set_y(ui_bienvenidosLabel, -173);
    lv_obj_set_align(ui_bienvenidosLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bienvenidosLabel, "Bienvenidos ");
    lv_obj_set_style_text_color(ui_bienvenidosLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bienvenidosLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bienvenidosLabel, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aLabel = lv_label_create(ui_splashScreen);
    lv_obj_set_width(ui_aLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aLabel, -2);
    lv_obj_set_y(ui_aLabel, -121);
    lv_obj_set_align(ui_aLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aLabel, "a");
    lv_obj_set_style_text_color(ui_aLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aLabel, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tanariDPLabel = lv_label_create(ui_splashScreen);
    lv_obj_set_width(ui_tanariDPLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tanariDPLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tanariDPLabel, 0);
    lv_obj_set_y(ui_tanariDPLabel, -68);
    lv_obj_set_align(ui_tanariDPLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tanariDPLabel, "Tanari DP");
    lv_obj_set_style_text_color(ui_tanariDPLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tanariDPLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tanariDPLabel, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iniciarButton = lv_button_create(ui_splashScreen);
    lv_obj_set_width(ui_iniciarButton, 150);
    lv_obj_set_height(ui_iniciarButton, 60);
    lv_obj_set_x(ui_iniciarButton, 1);
    lv_obj_set_y(ui_iniciarButton, 166);
    lv_obj_set_align(ui_iniciarButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iniciarButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_iniciarButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_iniciarButton, lv_color_hex(0xD0D0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_iniciarButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iniciarLabel = lv_label_create(ui_iniciarButton);
    lv_obj_set_width(ui_iniciarLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iniciarLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_iniciarLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iniciarLabel, "INICIAR");
    lv_obj_set_style_text_color(ui_iniciarLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iniciarLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iniciarLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_iniciarButton, ui_event_iniciarButton, LV_EVENT_ALL, NULL);

}

void ui_splashScreen_screen_destroy(void)
{
    if(ui_splashScreen) lv_obj_del(ui_splashScreen);

    // NULL screen variables
    ui_splashScreen = NULL;
    ui_bienvenidoImagen = NULL;
    ui_bienvenidosLabel = NULL;
    ui_aLabel = NULL;
    ui_tanariDPLabel = NULL;
    ui_iniciarButton = NULL;
    ui_iniciarLabel = NULL;

}
